FROM nginx:1.20

# IMPORTANT NOTICE
# THIS TEMPLATE WILL COPY THE DEFAULT CONFIG INTO YOUR PERSISTENT FOLDER
# AFTER THAT YOUR PERSISTENT FOLDER AND THE NGINX CONFIG FOLDER WILL BE LINKED
# THIS MEANS YOU CAN CHANGE THE CONFIGURATION FROM THE FILE BROWSER :-)

COPY html /usr/share/nginx/html
COPY config /etc/nginx

EXPOSE 80

CMD nginx -g 'daemon off;'
