FROM nginxinc/nginx-unprivileged:stable-alpine

# IMPORTANT NOTICE
# THIS TEMPLATE WILL COPY THE DEFAULT CONFIG INTO YOUR PERSISTENT FOLDER
# AFTER THAT YOUR PERSISTENT FOLDER AND THE NGINX CONFIG FOLDER WILL BE LINKED
# THIS MEANS YOU CAN CHANGE THE CONFIGURATION FROM THE FILE BROWSER :-)

WORKDIR /usr/src/nginx
COPY . .

EXPOSE 8080
USER 0
RUN chown -R 101:101 /etc/nginx
RUN chown -R 101:101 /usr/share/nginx/html

#ENTRYPOINT /usr/src/nginx/run.sh

USER 101
CMD nginx -g 'daemon off;'
